# Generated by Django 5.2 on 2025-06-18 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('function_called', models.CharField(max_length=100)),
                ('gas_used', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail')], max_length=10)),
                ('block_number', models.PositiveBigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('system_id', models.CharField(blank=True, max_length=100, null=True)),
                ('table_id', models.CharField(blank=True, max_length=100, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
