# Generated by Django 5.2 on 2025-06-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchaintransactionlog',
            name='action_type',
            field=models.CharField(choices=[('store', 'Store Data'), ('update', 'Update Data'), ('create', 'Create Ledger'), ('delete', 'Delete Entry'), ('read', 'Read Data'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='blockchaintransactionlog',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='blockchaintransactionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
