# Generated by Django 5.2 on 2025-06-25 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_blockchaintransactionlog_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_id', models.CharField(db_index=True, max_length=100)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('SYSTEM', 'System'), ('DATABASE', 'Database'), ('AGENT', 'Agent')], default='AGENT', max_length=10)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
