# Generated by Django 5.2 on 2025-06-25 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0003_monitoredevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('system_id', models.CharField(max_length=100)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='CRITICAL', max_length=20)),
                ('source', models.CharField(default='AnomalyEngine', max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
