# Generated by Django 5.2 on 2025-05-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
