# Generated by Django 5.2 on 2025-05-03 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(upload_to='system_profiles/')),
                ('url', models.URLField()),
                ('data_type', models.CharField(max_length=255)),
                ('system_type', models.CharField(max_length=255)),
                ('num_admins', models.IntegerField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('registered_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='registration.registeredsystem')),
            ],
        ),
    ]
