# Generated by Django 5.2 on 2025-05-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredsystem',
            name='profile_photo',
            field=models.ImageField(blank=True, default='system_profiles/default.jpg', null=True, upload_to='system_profiles/'),
        ),
    ]
